version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: diasoft
      POSTGRES_PASSWORD: diasoft
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
