spring:

  application:
    name: rest-service

  main:
    banner-mode: "off"

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}
    driver-class-name: org.postgresql.Driver
    name: ${postgres.database}
    username: ${postgres.username}
    password: ${postgres.password}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none


  postgres:
    host:
    port: 5432
    database: postgresql
    username: diasoft
    password: diasoft
    pool:
      initial-size: 5
      max-idle-time: 10s
    liquibase:
      enabled: true
