spring:
#  liquibase:
#    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#    hibernate:
#      ddl-auto: none

  sql:
    init:
      schema-locations: ${DB_SCHEMA}

